syntax = "proto3";

// simple flat data structure for communicating game state
// (This is duplicated from clientside; obviously this would be better broken off and shared b/w them)
message GameStateMessage {
  int32 currentMode = 1;

  double pacmanPositionX = 2;
  double pacmanPositionY = 3;
  int32 pacmanOrientation = 4;
  bool pacmanIsChomping = 5;
  bool pacmanIsHidden = 6;

  bool ghostsAreScattering = 7;

  double pinkyPositionX = 8;
  double pinkyPositionY = 9;
  int32 pinkyOrientation = 10;
  bool pinkyIsDead = 11;
  bool pinkyIsHidden = 12;

  double inkyPositionX = 13;
  double inkyPositionY = 14;
  int32 inkyOrientation = 15;
  bool inkyIsDead = 16;
  bool inkyIsHidden = 17;

  double blinkyPositionX = 18;
  double blinkyPositionY = 19;
  int32 blinkyOrientation = 20;
  bool blinkyIsDead = 21;
  bool blinkyIsHidden = 22;

  double clydePositionX = 23;
  double clydePositionY = 24;
  int32 clydeOrientation = 25;
  bool clydeIsDead = 26;
  bool clydeIsHidden = 27;

  map<uint32, uint32> items = 28;
}